name       : keepassxc
version    : 2.7.0
release    : 36
homepage   : https://keepassxc.org
source     :
    - https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/keepassxc-2.7.0-src.tar.xz : 83be76890904cd6703343fa097d68bcfdd99bb525cf518fa62a7df9293026aa7
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - CC0-1.0
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.1-only
    - MIT
    - OFL-1.1
component  : security
summary    : KeePassXC is a community fork of KeePassX with the goal to extend and improve it with new features and bugfixes to provide a feature-rich, fully cross-platform and modern open-source password
    manager.
description: |
    KeePassXC is a community fork of KeePassX with the goal to extend and improve it with new features and bugfixes to provide a feature-rich, fully cross-platform and modern open-source password manager.
replaces   :
    - keepassx
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(botan-2)
    - pkgconfig(libargon2)
    - pkgconfig(libpcsclite)
    - pkgconfig(libqrencode)
    - pkgconfig(libusb-1.0)
    - pkgconfig(xtst)
    - libyubikey-devel
setup      : |
    %cmake_ninja -DWITH_XC_AUTOTYPE=ON \
                 -DWITH_XC_BROWSER=ON \
                 -DWITH_XC_DOCS=OFF \
                 -DWITH_XC_NETWORKING=ON \
                 -DWITH_XC_SSHAGENT=ON \
                 -DWITH_XC_UPDATECHECK=OFF \
                 -DWITH_XC_YUBIKEY=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
