name       : keepassx
version    : 2.5.4
release    : 27
homepage   : https://keepassxc.org
source     :
    - https://github.com/keepassxreboot/keepassxc/releases/download/2.5.4/keepassxc-2.5.4-src.tar.xz : a55e0801c318b02b1ac4e16e9b7a87ccfa7b039ea60d2c62610bd1bbbdd6cd4a
license    :
    - BSD-3-Clause
    - BSL-1.0
    - CC0-1.0
    - GPL-2.0
    - LGPL-2.1
    - LGPL-3.0
    - Public Domain
component  : security
summary    : KeePassX is an application for people with extremely high demands on secure personal data management. This package utilizes the KeepassXC fork.
description: |
    KeePassXC is a community fork of KeePassX with the goal to extend and improve it with new features and bugfixes to provide a feature-rich, fully cross-platform and modern open-source password manager.
builddeps  :
    - pkgconfig(libargon2)
    - pkgconfig(libqrencode)
    - pkgconfig(libsodium)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - pkgconfig(ykpers-1)
    - libgcrypt-devel
    - libyubikey-devel
setup      : |
    %cmake_ninja -DWITH_XC_AUTOTYPE=ON \
                 -DWITH_XC_BROWSER=ON \
                 -DWITH_XC_NETWORKING=ON \
                 -DWITH_XC_SSHAGENT=ON \
                 -DWITH_XC_UPDATECHECK=OFF \
                 -DWITH_XC_YUBIKEY=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    # This directory is empty ATM. Duh
    rmdir $installdir/usr/share/keepassxc/docs/man
check      : |
    set -m
    %ninja_check
