name       : keepassx
version    : 2.0.3
release    : 3
source     :
    - https://www.keepassx.org/releases/2.0.3/keepassx-2.0.3.tar.gz : 23ffb4ae360c58aa139943442d175bc6b8f08e6a876ae76c4543ab983a6647c5
license    : GPL-2.0
component  : security
summary    : KeePassX is an application for people with extremely high demands on secure personal data management.
description: |
    KeePassX is an application for people with extremely high demands on secure personal data management.
builddeps  :
    - pkgconfig(QtCore)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xtst)
    - libgcrypt-devel
setup      : |
    sed -i 's:x-keepass2:x-keepass2;application/octet-stream:g' share/linux/keepassx.desktop
    %cmake -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 .
build      : |
    %make
install    : |
    %make_install
