name       : keepassx
version    : 2.2.0
release    : 7
source     :
    - https://github.com/keepassxreboot/keepassxc/releases/download/2.2.0/keepassxc-2.2.0-src.tar.xz : 71c47ebd9a661fc439c61566e4a4aa482e4d463c0eaa4f7562e7216eb0327e59
license    :
    - BSD-3-Clause
    - Boost-1.0
    - CC0
    - GPL-2.0
    - LGPL-2.1
    - LGPL-3.0
    - Public-Domain
component  : security
summary    : KeePassX is an application for people with extremely high demands on secure personal data management. This package utilizes the KeepassXC fork.
description: |
    KeePassXC is a community fork of KeePassX with the goal to extend and improve it with new features and bugfixes to provide a feature-rich, fully cross-platform and modern open-source password manager.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - pkgconfig(ykpers-1) 
    - libgcrypt-devel
    - libyubikey-devel
setup      : |
    sed -i 's:x-keepass2:x-keepass2;application/octet-stream:g' share/linux/keepassxc.desktop
    %cmake . -DWITH_XC_AUTOTYPE=ON \
             -DWITH_XC_HTTP=ON \
             -DWITH_XC_YUBIKEY=ON \
             -DCMAKE_BUILD_TYPE=Release
build      : |
    %make
install    : |
    %make_install
