name       : keepassx
version    : 2.3.0
release    : 11
source     :
    - https://github.com/keepassxreboot/keepassxc/releases/download/2.3.0/keepassxc-2.3.0-src.tar.xz : ec5858daeaa05386a614b799d5daf01c634205844647e2f9d25aaf655d2adbec
license    :
    - BSD-3-Clause
    - BSL-1.0
    - CC0-1.0
    - GPL-2.0
    - LGPL-2.1
    - LGPL-3.0
    - Public Domain
component  : security
summary    : KeePassX is an application for people with extremely high demands on secure personal data management. This package utilizes the KeepassXC fork.
description: |
    KeePassXC is a community fork of KeePassX with the goal to extend and improve it with new features and bugfixes to provide a feature-rich, fully cross-platform and modern open-source password manager.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libargon2)
    - pkgconfig(libsodium)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - pkgconfig(ykpers-1)
    - libyubikey-devel
setup      : |
    sed -i 's:x-keepass2:x-keepass2;application/octet-stream:g' share/linux/org.keepassxc.KeePassXC.desktop
    %cmake . -DWITH_XC_AUTOTYPE=ON \
             -DWITH_XC_BROWSER=ON \
             -DWITH_XC_YUBIKEY=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    export LC_ALL=en_US.utf8
    %make test

