name       : keepassx
version    : 2.0
release    : 1
source     :
    - https://www.keepassx.org/releases/2.0/keepassx-2.0.tar.gz : 0eb40fac3a44d8283dfc1ee28cc6de5c660b22ab975472de82c2b04675c822e6
license    : GPL-2.0
summary    : KeePassX is an application for people with extremely high demands on secure personal data management.
description: |
    KeePassX is an application for people with extremely high demands on secure personal data management.
builddeps  :
    - pkgconfig(QtCore)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xtst)
    - libgcrypt-devel
setup      : |
    ln -s /usr/bin/rcc-qt4 /usr/bin/rcc
    %cmake .
build      : |
    %make
install    : |
    %make_install
