name       : keepassx
version    : 2.2.2
release    : 9
source     :
    - https://github.com/keepassxreboot/keepassxc/releases/download/2.2.2/keepassxc-2.2.2-src.tar.xz : 2f55784f7e6d3a840575e1768a3e5ae03986c2f6a70029dd6b9f9bb0fa443473
license    :
    - BSD-3-Clause
    - BSL-1.0
    - CC0-1.0
    - GPL-2.0
    - LGPL-2.1
    - LGPL-3.0
    - Public Domain
component  : security
summary    : KeePassX is an application for people with extremely high demands on secure personal data management. This package utilizes the KeepassXC fork.
description: |
    KeePassXC is a community fork of KeePassX with the goal to extend and improve it with new features and bugfixes to provide a feature-rich, fully cross-platform and modern open-source password manager.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - pkgconfig(ykpers-1)
    - libgcrypt-devel
    - libyubikey-devel
setup      : |
    sed -i 's:x-keepass2:x-keepass2;application/octet-stream:g' share/linux/org.keepassxc.desktop
    %cmake . -DWITH_XC_AUTOTYPE=ON \
             -DWITH_XC_HTTP=ON \
             -DWITH_XC_YUBIKEY=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    export LC_ALL=en_US.utf8
    %make test
