name       : keepassx
version    : 2.6.4
release    : 32
homepage   : https://keepassxc.org
source     :
    - https://github.com/keepassxreboot/keepassxc/releases/download/2.6.4/keepassxc-2.6.4-src.tar.xz : e536e2a71c90fcf264eb831fb1a8b518ee1b03829828f862eeea748d3310f82b
license    :
    # See https://github.com/keepassxreboot/keepassxc/blob/develop/COPYING
    - BSD-3-Clause
    - BSL-1.0
    - CC0-1.0
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.0-only
    - LGPL-2.1-only
    - MIT
component  : security
summary    : KeePassX is an application for people with extremely high demands on secure personal data management. This package utilizes the KeepassXC fork.
description: |
    KeePassXC is a community fork of KeePassX with the goal to extend and improve it with new features and bugfixes to provide a feature-rich, fully cross-platform and modern open-source password manager.
builddeps  :
    - pkgconfig(libargon2)
    - pkgconfig(libqrencode)
    - pkgconfig(libsodium)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - pkgconfig(ykpers-1)
    - libgcrypt-devel
    - libyubikey-devel
setup      : |
    %cmake_ninja -DWITH_XC_AUTOTYPE=ON \
                 -DWITH_XC_BROWSER=ON \
                 -DWITH_XC_DOCS=OFF \
                 -DWITH_XC_NETWORKING=ON \
                 -DWITH_XC_SSHAGENT=ON \
                 -DWITH_XC_UPDATECHECK=OFF \
                 -DWITH_XC_YUBIKEY=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
