name       : keepassx
version    : 2.1.4
release    : 6
source     :
    - https://github.com/keepassxreboot/keepassxc/releases/download/2.1.4/keepassxc-2.1.4-src.tar.xz : 22c564fab78bd960b9af5a779c7bd59f0cc04a9988b00c6b82329059e59b0035
license    :
    - BSD-3-Clause
    - Boost-1.0
    - CC0
    - GPL-2.0
    - LGPL-2.1
    - LGPL-3.0
    - Public-Domain
component  : security
summary    : KeePassX is an application for people with extremely high demands on
    secure personal data management. This package utilizes the KeepassXC fork.
description: |
    KeePassX is an application for people with extremely high demands on secure personal data management. This package utilizes the KeepassXC fork.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - libgcrypt-devel
    - libyubikey-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-bug-Fix-building-with-Qt-5.9-closes-528.patch
    sed -i 's:x-keepass2:x-keepass2;application/octet-stream:g' share/linux/keepassxc.desktop
    %cmake -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON .
build      : |
    %make
install    : |
    %make_install
