name       : keepassx
version    : 2.0.2
release    : 2
source     :
    - https://www.keepassx.org/releases/2.0.2/keepassx-2.0.2.tar.gz : 204bdcf49c72078cd6f02b4f29b062923cca9e7b2d3551f2bf352763daa236b8
license    : GPL-2.0
summary    : KeePassX is an application for people with extremely high demands on secure personal data management.
description: |
    KeePassX is an application for people with extremely high demands on secure personal data management.
builddeps  :
    - pkgconfig(QtCore)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xtst)
    - libgcrypt-devel
setup      : |
    ln -s /usr/bin/rcc-qt4 /usr/bin/rcc
    %cmake .
build      : |
    %make
install    : |
    %make_install
