name       : keepassx
version    : 2.4.0
release    : 18
homepage   : https://keepassxc.org
source     :
    - https://github.com/keepassxreboot/keepassxc/releases/download/2.4.0/keepassxc-2.4.0-src.tar.xz : 081ff1a34da8e0e8db951b5d70824d7a2b3d299ed4ae54e6ddc1e3ac176b95a8
license    :
    - BSD-3-Clause
    - BSL-1.0
    - CC0-1.0
    - GPL-2.0
    - LGPL-2.1
    - LGPL-3.0
    - Public Domain
component  : security
summary    : KeePassX is an application for people with extremely high demands on secure personal data management. This package utilizes the KeepassXC fork.
description: |
    KeePassXC is a community fork of KeePassX with the goal to extend and improve it with new features and bugfixes to provide a feature-rich, fully cross-platform and modern open-source password manager.
builddeps  :
    - pkgconfig(libargon2)
    - pkgconfig(libqrencode)
    - pkgconfig(libsodium)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - pkgconfig(ykpers-1)
    - libgcrypt-devel
    - libyubikey-devel
setup      : |
    # The KeeShare patch can be removed once 2.4.1 will be out
    %patch -p1 < $pkgfiles/0001-Fix-build-if-KeeShare-is-disabled.patch
    %cmake_ninja -DWITH_XC_AUTOTYPE=ON \
                 -DWITH_XC_BROWSER=ON \
                 -DWITH_XC_NETWORKING=ON \
                 -DWITH_XC_YUBIKEY=ON \
                 -DWITH_XC_SSHAGENT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    set -m
    %ninja_check
